-- Sync settings with reference translations and add global links
-- Bengali
INSERT INTO public.settings (key, value) VALUES 
('bn.brand', 'ITFair'),
('bn.brand_sub', 'AUTHORIZED BD'),
('bn.hero_kicker', 'আমাদের সেবাসমূহ'),
('bn.hero_title', 'অনুগ্রহ করে আপনার কাঙ্ক্ষিত সেবা বেছে নিন'),
('bn.main_title', 'AI দিয়ে ওয়েবসাইট ও অ্যাপ মিনিটের মধ্যে বানান'),
('bn.main_desc', 'Lovable Pro Plan — কোডিং ছাড়াই AI দিয়ে ওয়েবসাইট, অ্যাপ ও SaaS বানান।'),
('bn.cta_text', 'প্যাকেজ দেখুন'),
('bn.trial_label', 'TRIAL PACKAGE'),
('bn.trial_title', 'ট্রায়াল প্যাকেজ'),
('bn.trial_desc', 'ভিডিও দেখে ডেমো করুন, তারপর ট্রায়াল নিন'),
('bn.trial_30_text', '১ ঘণ্টা'),
('bn.trial_30_price', '৯০'),
('bn.trial_10_text', '১০ মিনিট'),
('bn.trial_10_price', '৫০'),
('bn.trial_buy', '১ ঘণ্টা ট্রায়াল কিনুন — ১৯০'),
('bn.trial_free', '১০ মিনিট ফ্রি ট্রায়াল নিন (৬০)'),
('bn.pricing_kicker', 'PRICING'),
('bn.pricing_title', 'আপনার জন্য সেরা প্যাকেজ'),
('bn.pricing_desc', 'সকল প্যাকেজ Lovable Pro আনলিমিটেড অ্যাক্সেস'),
('bn.support_text', 'আমাদের সাথে যোগাযোগ করুন'),
('bn.whatsapp', 'WhatsApp এ যোগাযোগ'),
('bn.footer', '© 2026 ITFair. All rights reserved.'),
('bn.nav_services', 'সার্ভিস'),
('bn.nav_packages', 'প্যাকেজ'),
('bn.nav_trial', 'ফ্রি ট্রায়াল'),
('bn.nav_offer', 'অফার দেখুন'),
('bn.nav_download', 'ডাউনলোড'),
('bn.nav_help', 'হেল্পলাইন'),
('bn.video_title', 'আমার সেবার ভিডিওটি দেখুন'),
('bn.video_desc', 'ভিডিও দেখে শিখুন — কীভাবে সব কিছু সহজে করবেন'),
('bn.authorized', 'AUTHORIZED · BANGLADESH'),
('bn.trial_access', 'প্যাকেজ কিনলে সাথে সাথে অ্যাক্সেস'),
('bn.trial_start', 'শুরু ও ফিচার ট্রায়াল'),
('bn.download_extension', 'এক্সটেনশন ডাউনলোড করুন'),
('bn.no_renew', 'অটোমেটিক রিনিউ নেই · সম্পূর্ণ নিরাপদ'),
('bn.trust_payment', 'নিরাপদ পেমেন্ট'),
('bn.trust_support', '২৪/৭ সাপোর্ট'),
('bn.trust_delivery', 'দ্রুতগতির ডেলিভারি'),
('bn.trust_guarantee', '১০০% গ্যারান্টি'),
('bn.package_details', 'বিস্তারিত দেখুন'),
('bn.buy_now', 'BUY NOW'),
('bn.contact_desc', 'WhatsApp এ আমাদের সাথে যোগাযোগ করুন — আমরা দ্রুত উত্তর দেব।'),
('bn.support_email', 'Anydesk Support'),
('bn.support_whatsapp', 'ITFair Support'),
('bn.order_title', 'অর্ডার করুন'),
('bn.your_name', 'আপনার নাম'),
('bn.phone', 'মোবাইল নম্বর'),
('bn.note', 'নোট (ঐচ্ছিক)'),
('bn.submit_order', 'অর্ডার সাবমিট'),
('bn.close', 'বন্ধ করুন'),
('bn.save', 'SAVE'),
('bn.days', 'দিন'),
('bn.hours', 'ঘণ্টা'),
('bn.minutes', 'মিনিট')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- English
INSERT INTO public.settings (key, value) VALUES 
('en.brand', 'ITFair'),
('en.brand_sub', 'AUTHORIZED BD'),
('en.hero_kicker', 'OUR SERVICES'),
('en.hero_title', 'Choose the service you need'),
('en.main_title', 'Build websites and apps in minutes with AI'),
('en.main_desc', 'Lovable Pro Plan — build websites, apps and SaaS with AI without coding.'),
('en.cta_text', 'View Packages'),
('en.trial_label', 'TRIAL PACKAGE'),
('en.trial_title', 'Trial Package'),
('en.trial_desc', 'Watch the demo video, then start your trial'),
('en.trial_30_text', '1 hour'),
('en.trial_30_price', '90'),
('en.trial_10_text', '10 minutes'),
('en.trial_10_price', '50'),
('en.trial_buy', 'Buy 1 hour trial — 190'),
('en.trial_free', 'Get 10 minutes free trial (60)'),
('en.pricing_kicker', 'PRICING'),
('en.pricing_title', 'The best package for you'),
('en.pricing_desc', 'All packages include unlimited Lovable Pro access'),
('en.support_text', 'Contact us'),
('en.whatsapp', 'Contact on WhatsApp'),
('en.footer', '© 2026 ITFair. All rights reserved.'),
('en.nav_services', 'Services'),
('en.nav_packages', 'Packages'),
('en.nav_trial', 'Free Trial'),
('en.nav_offer', 'View Offers'),
('en.nav_download', 'Download'),
('en.nav_help', 'Help Line'),
('en.video_title', 'Watch our service video'),
('en.video_desc', 'Watch the video to learn how everything works'),
('en.authorized', 'AUTHORIZED · BANGLADESH'),
('en.trial_access', 'Instant access after purchase'),
('en.trial_start', 'Starter feature trial'),
('en.download_extension', 'Download Extension'),
('en.no_renew', 'No automatic renewal · Fully secure'),
('en.trust_payment', 'Secure Payment'),
('en.trust_support', '24/7 Support'),
('en.trust_delivery', 'Fast Delivery'),
('en.trust_guarantee', '100% Guarantee'),
('en.package_details', 'View Details'),
('en.buy_now', 'BUY NOW'),
('en.contact_desc', 'Contact us on WhatsApp — we will reply quickly.'),
('en.support_email', 'Anydesk Support'),
('en.support_whatsapp', 'ITFair Support'),
('en.order_title', 'Place Order'),
('en.your_name', 'Your Name'),
('en.phone', 'Mobile Number'),
('en.note', 'Note (optional)'),
('en.submit_order', 'Submit Order'),
('en.close', 'Close'),
('en.save', 'SAVE'),
('en.days', 'days'),
('en.hours', 'hours'),
('en.minutes', 'minutes')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Global Links
INSERT INTO public.settings (key, value) VALUES 
('whatsapp_url', 'https://wa.me/8801700000000'),
('email', 'support@itfair.com'),
('extension_url', 'https://chrome.google.com/webstore/detail/...'),
('trial_url', 'https://itfair.com/trial'),
('facebook_url', 'https://facebook.com/itfair'),
('telegram_url', 'https://t.me/itfair')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Cleanup
UPDATE public.settings SET value = REPLACE(value, E'\u2063', '');
UPDATE public.services SET title = REPLACE(title, E'\u2063', ''), description = REPLACE(description, E'\u2063', '');
UPDATE public.packages SET name = REPLACE(name, E'\u2063', ''), duration = REPLACE(duration, E'\u2063', ''), description = REPLACE(description, E'\u2063', ''), badge = REPLACE(badge, E'\u2063', ''), type = REPLACE(type, E'\u2063', '');
