ALTER TABLE public.packages ADD COLUMN IF NOT EXISTS button TEXT DEFAULT 'BUY NOW';
ALTER TABLE public.packages ADD COLUMN IF NOT EXISTS name_pt TEXT DEFAULT '';
ALTER TABLE public.packages ADD COLUMN IF NOT EXISTS duration_pt TEXT DEFAULT '';
ALTER TABLE public.packages ADD COLUMN IF NOT EXISTS badge_pt TEXT DEFAULT '';
ALTER TABLE public.packages ADD COLUMN IF NOT EXISTS type_pt TEXT DEFAULT '';
ALTER TABLE public.packages ADD COLUMN IF NOT EXISTS description_pt TEXT DEFAULT '';
ALTER TABLE public.services ADD COLUMN IF NOT EXISTS title_pt TEXT DEFAULT '';
ALTER TABLE public.services ADD COLUMN IF NOT EXISTS description_pt TEXT DEFAULT '';
